module.exports = {
	START: 'START',
	TERMINATE: 'TERMINATE',
	SESSION_CREATED: 'SESSION_CREATED',
	SESSION_TERMINATED: 'SESSION_TERMINATED',
	MRCP_MESSAGE: 'MRCP_MESSAGE',	
	TTS_FILE_READY: 'TTS_FILE_READY',
	MEDIA_OPERATION_COMPLETED: 'MEDIA_OPERATION_COMPLETE',
	RECOGNITION_COMPLETED: 'RECOGNITION_COMPLETED',
	RECOGNITION_COMPLETED_WITH_ERROR: 'RECOGNITION_COMPLETED_WITH_ERROR',
}
