module.exports = {
	START: 'START',
	TERMINATE: 'TERMINATE',
	SESSION_CREATED: 'SESSION_CREATED',
	SESSION_TERMINATED: 'SESSION_TERMINATED',
	MRCP_MESSAGE: 'MRCP_MESSAGE',	
	TTS_FILE_READY: 'TTS_FILE_READY',
}
